//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.12 at 09:23:49 PM EST 
//


package com.f9g4.businessobjects.services;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.jvnet.jaxb2_commons.lang.CopyStrategy;
import org.jvnet.jaxb2_commons.lang.CopyTo;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBCopyStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for Company complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Company">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="companyId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="companyName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="companyType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="customerNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="membershipType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="memberSince" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="memberExpirationDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="langCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="activeFlag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Company", propOrder = {
    "companyId",
    "companyName",
    "companyType",
    "customerNumber",
    "membershipType",
    "memberSince",
    "memberExpirationDate",
    "langCode",
    "activeFlag"
})
@XmlRootElement(name = "Company")
public class Company implements Cloneable, CopyTo, Equals, HashCode, ToString
{

    @XmlElement(required = true)
    protected BigInteger companyId;
    @XmlElement(required = true)
    protected String companyName;
    @XmlElement(required = true)
    protected String companyType;
    @XmlElement(required = true)
    protected String customerNumber;
    @XmlElement(required = true)
    protected String membershipType;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar memberSince;
    @XmlElement(required = true)
    protected String memberExpirationDate;
    @XmlElement(required = true)
    protected String langCode;
    @XmlElement(required = true)
    protected String activeFlag;

    /**
     * Default no-arg constructor
     * 
     */
    public Company() {
        super();
    }

    /**
     * Fully-initialising value constructor
     * 
     */
    public Company(final BigInteger companyId, final String companyName, final String companyType, final String customerNumber, final String membershipType, final XMLGregorianCalendar memberSince, final String memberExpirationDate, final String langCode, final String activeFlag) {
        this.companyId = companyId;
        this.companyName = companyName;
        this.companyType = companyType;
        this.customerNumber = customerNumber;
        this.membershipType = membershipType;
        this.memberSince = memberSince;
        this.memberExpirationDate = memberExpirationDate;
        this.langCode = langCode;
        this.activeFlag = activeFlag;
    }

    /**
     * Gets the value of the companyId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCompanyId() {
        return companyId;
    }

    /**
     * Sets the value of the companyId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCompanyId(BigInteger value) {
        this.companyId = value;
    }

    /**
     * Gets the value of the companyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * Sets the value of the companyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyName(String value) {
        this.companyName = value;
    }

    /**
     * Gets the value of the companyType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyType() {
        return companyType;
    }

    /**
     * Sets the value of the companyType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyType(String value) {
        this.companyType = value;
    }

    /**
     * Gets the value of the customerNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerNumber() {
        return customerNumber;
    }

    /**
     * Sets the value of the customerNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerNumber(String value) {
        this.customerNumber = value;
    }

    /**
     * Gets the value of the membershipType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMembershipType() {
        return membershipType;
    }

    /**
     * Sets the value of the membershipType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMembershipType(String value) {
        this.membershipType = value;
    }

    /**
     * Gets the value of the memberSince property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMemberSince() {
        return memberSince;
    }

    /**
     * Sets the value of the memberSince property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMemberSince(XMLGregorianCalendar value) {
        this.memberSince = value;
    }

    /**
     * Gets the value of the memberExpirationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMemberExpirationDate() {
        return memberExpirationDate;
    }

    /**
     * Sets the value of the memberExpirationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMemberExpirationDate(String value) {
        this.memberExpirationDate = value;
    }

    /**
     * Gets the value of the langCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLangCode() {
        return langCode;
    }

    /**
     * Sets the value of the langCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLangCode(String value) {
        this.langCode = value;
    }

    /**
     * Gets the value of the activeFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActiveFlag() {
        return activeFlag;
    }

    /**
     * Sets the value of the activeFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActiveFlag(String value) {
        this.activeFlag = value;
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            BigInteger theCompanyId;
            theCompanyId = this.getCompanyId();
            strategy.appendField(locator, this, "companyId", buffer, theCompanyId);
        }
        {
            String theCompanyName;
            theCompanyName = this.getCompanyName();
            strategy.appendField(locator, this, "companyName", buffer, theCompanyName);
        }
        {
            String theCompanyType;
            theCompanyType = this.getCompanyType();
            strategy.appendField(locator, this, "companyType", buffer, theCompanyType);
        }
        {
            String theCustomerNumber;
            theCustomerNumber = this.getCustomerNumber();
            strategy.appendField(locator, this, "customerNumber", buffer, theCustomerNumber);
        }
        {
            String theMembershipType;
            theMembershipType = this.getMembershipType();
            strategy.appendField(locator, this, "membershipType", buffer, theMembershipType);
        }
        {
            XMLGregorianCalendar theMemberSince;
            theMemberSince = this.getMemberSince();
            strategy.appendField(locator, this, "memberSince", buffer, theMemberSince);
        }
        {
            String theMemberExpirationDate;
            theMemberExpirationDate = this.getMemberExpirationDate();
            strategy.appendField(locator, this, "memberExpirationDate", buffer, theMemberExpirationDate);
        }
        {
            String theLangCode;
            theLangCode = this.getLangCode();
            strategy.appendField(locator, this, "langCode", buffer, theLangCode);
        }
        {
            String theActiveFlag;
            theActiveFlag = this.getActiveFlag();
            strategy.appendField(locator, this, "activeFlag", buffer, theActiveFlag);
        }
        return buffer;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof Company)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final Company that = ((Company) object);
        {
            BigInteger lhsCompanyId;
            lhsCompanyId = this.getCompanyId();
            BigInteger rhsCompanyId;
            rhsCompanyId = that.getCompanyId();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "companyId", lhsCompanyId), LocatorUtils.property(thatLocator, "companyId", rhsCompanyId), lhsCompanyId, rhsCompanyId)) {
                return false;
            }
        }
        {
            String lhsCompanyName;
            lhsCompanyName = this.getCompanyName();
            String rhsCompanyName;
            rhsCompanyName = that.getCompanyName();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "companyName", lhsCompanyName), LocatorUtils.property(thatLocator, "companyName", rhsCompanyName), lhsCompanyName, rhsCompanyName)) {
                return false;
            }
        }
        {
            String lhsCompanyType;
            lhsCompanyType = this.getCompanyType();
            String rhsCompanyType;
            rhsCompanyType = that.getCompanyType();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "companyType", lhsCompanyType), LocatorUtils.property(thatLocator, "companyType", rhsCompanyType), lhsCompanyType, rhsCompanyType)) {
                return false;
            }
        }
        {
            String lhsCustomerNumber;
            lhsCustomerNumber = this.getCustomerNumber();
            String rhsCustomerNumber;
            rhsCustomerNumber = that.getCustomerNumber();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "customerNumber", lhsCustomerNumber), LocatorUtils.property(thatLocator, "customerNumber", rhsCustomerNumber), lhsCustomerNumber, rhsCustomerNumber)) {
                return false;
            }
        }
        {
            String lhsMembershipType;
            lhsMembershipType = this.getMembershipType();
            String rhsMembershipType;
            rhsMembershipType = that.getMembershipType();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "membershipType", lhsMembershipType), LocatorUtils.property(thatLocator, "membershipType", rhsMembershipType), lhsMembershipType, rhsMembershipType)) {
                return false;
            }
        }
        {
            XMLGregorianCalendar lhsMemberSince;
            lhsMemberSince = this.getMemberSince();
            XMLGregorianCalendar rhsMemberSince;
            rhsMemberSince = that.getMemberSince();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "memberSince", lhsMemberSince), LocatorUtils.property(thatLocator, "memberSince", rhsMemberSince), lhsMemberSince, rhsMemberSince)) {
                return false;
            }
        }
        {
            String lhsMemberExpirationDate;
            lhsMemberExpirationDate = this.getMemberExpirationDate();
            String rhsMemberExpirationDate;
            rhsMemberExpirationDate = that.getMemberExpirationDate();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "memberExpirationDate", lhsMemberExpirationDate), LocatorUtils.property(thatLocator, "memberExpirationDate", rhsMemberExpirationDate), lhsMemberExpirationDate, rhsMemberExpirationDate)) {
                return false;
            }
        }
        {
            String lhsLangCode;
            lhsLangCode = this.getLangCode();
            String rhsLangCode;
            rhsLangCode = that.getLangCode();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "langCode", lhsLangCode), LocatorUtils.property(thatLocator, "langCode", rhsLangCode), lhsLangCode, rhsLangCode)) {
                return false;
            }
        }
        {
            String lhsActiveFlag;
            lhsActiveFlag = this.getActiveFlag();
            String rhsActiveFlag;
            rhsActiveFlag = that.getActiveFlag();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "activeFlag", lhsActiveFlag), LocatorUtils.property(thatLocator, "activeFlag", rhsActiveFlag), lhsActiveFlag, rhsActiveFlag)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            BigInteger theCompanyId;
            theCompanyId = this.getCompanyId();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "companyId", theCompanyId), currentHashCode, theCompanyId);
        }
        {
            String theCompanyName;
            theCompanyName = this.getCompanyName();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "companyName", theCompanyName), currentHashCode, theCompanyName);
        }
        {
            String theCompanyType;
            theCompanyType = this.getCompanyType();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "companyType", theCompanyType), currentHashCode, theCompanyType);
        }
        {
            String theCustomerNumber;
            theCustomerNumber = this.getCustomerNumber();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "customerNumber", theCustomerNumber), currentHashCode, theCustomerNumber);
        }
        {
            String theMembershipType;
            theMembershipType = this.getMembershipType();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "membershipType", theMembershipType), currentHashCode, theMembershipType);
        }
        {
            XMLGregorianCalendar theMemberSince;
            theMemberSince = this.getMemberSince();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "memberSince", theMemberSince), currentHashCode, theMemberSince);
        }
        {
            String theMemberExpirationDate;
            theMemberExpirationDate = this.getMemberExpirationDate();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "memberExpirationDate", theMemberExpirationDate), currentHashCode, theMemberExpirationDate);
        }
        {
            String theLangCode;
            theLangCode = this.getLangCode();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "langCode", theLangCode), currentHashCode, theLangCode);
        }
        {
            String theActiveFlag;
            theActiveFlag = this.getActiveFlag();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "activeFlag", theActiveFlag), currentHashCode, theActiveFlag);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    public Object clone() {
        return copyTo(createNewInstance());
    }

    public Object copyTo(Object target) {
        final CopyStrategy strategy = JAXBCopyStrategy.INSTANCE;
        return copyTo(null, target, strategy);
    }

    public Object copyTo(ObjectLocator locator, Object target, CopyStrategy strategy) {
        final Object draftCopy = ((target == null)?createNewInstance():target);
        if (draftCopy instanceof Company) {
            final Company copy = ((Company) draftCopy);
            if (this.companyId!= null) {
                BigInteger sourceCompanyId;
                sourceCompanyId = this.getCompanyId();
                BigInteger copyCompanyId = ((BigInteger) strategy.copy(LocatorUtils.property(locator, "companyId", sourceCompanyId), sourceCompanyId));
                copy.setCompanyId(copyCompanyId);
            } else {
                copy.companyId = null;
            }
            if (this.companyName!= null) {
                String sourceCompanyName;
                sourceCompanyName = this.getCompanyName();
                String copyCompanyName = ((String) strategy.copy(LocatorUtils.property(locator, "companyName", sourceCompanyName), sourceCompanyName));
                copy.setCompanyName(copyCompanyName);
            } else {
                copy.companyName = null;
            }
            if (this.companyType!= null) {
                String sourceCompanyType;
                sourceCompanyType = this.getCompanyType();
                String copyCompanyType = ((String) strategy.copy(LocatorUtils.property(locator, "companyType", sourceCompanyType), sourceCompanyType));
                copy.setCompanyType(copyCompanyType);
            } else {
                copy.companyType = null;
            }
            if (this.customerNumber!= null) {
                String sourceCustomerNumber;
                sourceCustomerNumber = this.getCustomerNumber();
                String copyCustomerNumber = ((String) strategy.copy(LocatorUtils.property(locator, "customerNumber", sourceCustomerNumber), sourceCustomerNumber));
                copy.setCustomerNumber(copyCustomerNumber);
            } else {
                copy.customerNumber = null;
            }
            if (this.membershipType!= null) {
                String sourceMembershipType;
                sourceMembershipType = this.getMembershipType();
                String copyMembershipType = ((String) strategy.copy(LocatorUtils.property(locator, "membershipType", sourceMembershipType), sourceMembershipType));
                copy.setMembershipType(copyMembershipType);
            } else {
                copy.membershipType = null;
            }
            if (this.memberSince!= null) {
                XMLGregorianCalendar sourceMemberSince;
                sourceMemberSince = this.getMemberSince();
                XMLGregorianCalendar copyMemberSince = ((XMLGregorianCalendar) strategy.copy(LocatorUtils.property(locator, "memberSince", sourceMemberSince), sourceMemberSince));
                copy.setMemberSince(copyMemberSince);
            } else {
                copy.memberSince = null;
            }
            if (this.memberExpirationDate!= null) {
                String sourceMemberExpirationDate;
                sourceMemberExpirationDate = this.getMemberExpirationDate();
                String copyMemberExpirationDate = ((String) strategy.copy(LocatorUtils.property(locator, "memberExpirationDate", sourceMemberExpirationDate), sourceMemberExpirationDate));
                copy.setMemberExpirationDate(copyMemberExpirationDate);
            } else {
                copy.memberExpirationDate = null;
            }
            if (this.langCode!= null) {
                String sourceLangCode;
                sourceLangCode = this.getLangCode();
                String copyLangCode = ((String) strategy.copy(LocatorUtils.property(locator, "langCode", sourceLangCode), sourceLangCode));
                copy.setLangCode(copyLangCode);
            } else {
                copy.langCode = null;
            }
            if (this.activeFlag!= null) {
                String sourceActiveFlag;
                sourceActiveFlag = this.getActiveFlag();
                String copyActiveFlag = ((String) strategy.copy(LocatorUtils.property(locator, "activeFlag", sourceActiveFlag), sourceActiveFlag));
                copy.setActiveFlag(copyActiveFlag);
            } else {
                copy.activeFlag = null;
            }
        }
        return draftCopy;
    }

    public Object createNewInstance() {
        return new Company();
    }

}
