package com.f9g4.common.util;

public enum LookupTypeValueEnum {
	//registration status
	REG_STATUS_SYSTEM(252,"SYSTEM"), REG_STATUS_COMPLETED_FORM(431,"CF"), REG_STATUS_CONFIRMED(432, "CD"), 
	REG_STATUS_WAITING_FOR_COFIRMATION(433,"WC"), 
	REG_STATUS_REGSTRATION_COMPLETED(434, "RC"),REG_STATUS_RECOMMENDED(435, "RM"), REG_STATUS_DENIED(435,"DN"), SAMPLES_SUBMIT_COMPLETED(548,"SBSC"),
	
	//Rating for designer
	RATING_QUALITY_OF_WORK(459, "RQ11"), RATING_PRICING(460, "RQ21"), RATING_RELIABILITY(461, "RQ31"), RATING_CUSTOMIZATION(462, "RQ41"), 
	
	//Rating for company
	RATING_QUALITY_OF_COMMUNICATION(535,"RD11"),RATING_DENPENDABILITY(536,"RD21"),RATING_EXPECTATIONS_FROM_YOU(537,"RD31"),RATING_PAYMENT_TERMS(538,"RD41"),
	
	//User Type (Designer or Customer)
	USER_TYPE_DESIGNER(437, "DG"), USER_TYPE_CUSTOMER(438, "CT"),  
	
	//membership type
	MEMEBERSHIP_TYPE_STANDARD (436, "ST."),MEMEBERSHIP_TYPE_SILVER (529, "SL."),
	//Member Term Type 
	MEMEBER_TERM_TYPE_REGISTRATION (11, "COREG"), MEMEBER_TERM_TYPE_REGISTRATION_DESIGNER (11,"DESREG"), MEMEBER_TERM_TYPE_SALE (11, "COSALE"),
	
	//EMAIL_STATUS
	EMAIL_STATUS_SENT(15,"ST"), EMAIL_STATUS_SAVED_TO_DRAFT(15, "SD"), EMAIL_STATUS_READY_TO_SEND(15,"RD"),
	EMAIL_STATUS_ID_SENT(454,"ST"), EMAIL_STATUS_ID_SAVED_TO_DRAFT(455, "SD"), EMAIL_STATUS_ID_READY_TO_SEND(525,"RD"),
	
	//MESSAGE_STATUS
	MESSAGE_STATUS_READ(449,"RD"), MESSAGE_STATUS_UNREAD(450,"UD"), MESSAGE_STATUS_DRAFT(451,"DT"), MESSAGE_STATUS_DELETED(452,"DD"),MESSAGE_STATUS_ARCHIVE(453,"AV"),
	
	//Member Payment Status
	MEM_PAYMENT_STATUS_PROCESSING(406, "PRC"), MEM_PAYMENT_STATUS_PAID(407, "PAID"),  MEM_PAYMENT_STATUS_DUE (408, "DUE"),  MEM_PAYMENT_STATUS_REJECTED(409, "REJ"), MEM_PAYMENT_STATUS_PAYMENT_PENDING(529, "PP"),
	
	//board 
	BOARD_SALE_STATUS_PROCESSING(468, "PROC"), BOARD_SALE_STATUS_READY(469, "READY"), BOARD_SALE_STATUS_AVAILABLE(470, "AVAILABLE"), BOARD_SALE_STATUS_SOLD(471, "SOLD"), BOARD_SALE_STATUS_PAYMENT_PENDING(534, "PAYP"),   
	
	// Board Sale Type
	BOARD_SALE_TYPE_JPG(441, "JG"), 
	BOARD_SALE_TYPE_JPG_AI(442, "JA"), BOARD_SALE_TYPE_JPG_AI_SAMPLES(443, "JAS"), BOARD_SALE_TYPE_JPG_AI_SAPLES_CUSTOMIZATION(444, "JASC"),
	BOARD_SALE_TYPE_JPG_DXF(445, "JD"), BOARD_SALE_TYPE_JPG_AI_DXF(446, "JAD"), BOARD_SALE_TYPE_JPG_AI_SAMPLES_DXF(447, "JASD"), 
	BOARD_SALE_TYPE_JPG_AI_SAMPLES_CUSTOMIZATION_DXF(441, "JASCD"),
	
	//country code
	COUNTRY_US(238,"US1"),
	
	//language code
	LANGUAGE_US(277,"en2");
	;
	
	
		
	private final int typeId;
	private final String typeCode;
	
	public int getTypeId() {
		return typeId;
	}
	public String getTypeCode() {
		return typeCode;
	}
	LookupTypeValueEnum(int typeId, String typeCode){
		this.typeCode = typeCode;
		this.typeId = typeId;
	}
}