//Initialize the app and load the module
var app = angular.module('adminConsoleApp', ['ngAnimate','adminFilters','rzModule','multi-select','ui.bootstrap','ngModal','ngRoute','dialogs.main'])
	.config(['$locationProvider', function($locationProvider) {
		// use the HTML5 History API
		$locationProvider.html5Mode(true);
	}])
	.run(['$templateCache',function($templateCache){
  		$templateCache.put('/dialogs/custom.html','<div class="modal-header dialog-header-confirm"><h4 class="modal-title"><span class="glyphicon glyphicon-check"></span> Do you want to REJECT this submission?</h4></div><div class="modal-body"><ng-form name="nameDialog" novalidate role="form"><div class="form-group input-group-lg" ng-class="{true: \'has-error\'}[nameDialog.username.$dirty && nameDialog.username.$invalid]"><label class="control-label" for="course">Comment:</label><textarea class="form-control comment-input" name="comments" id="comments" ng-model="comments" required></textarea><span class="help-block">Enter your reason why you reject this submission.</span></div></ng-form></div><div class="modal-footer"><button type="button" class="btn btn-default" ng-click="save()" ng-disabled="(nameDialog.$dirty && nameDialog.$invalid) || nameDialog.$pristine">Yes</button><button type="button" class="btn btn-primary" ng-click="cancel()">No</button></div>');
  		$templateCache.put('/dialogs/custom2.html','<div class="modal-header"><h4 class="modal-title"><span class="glyphicon glyphicon-star"></span> Custom Dialog 2</h4></div><div class="modal-body"><label class="control-label" for="customValue">Custom Value:</label><input type="text" class="form-control" id="customValue" ng-model="data.val" ng-keyup="hitEnter($event)"><span class="help-block">Using "dialogsProvider.useCopy(false)" in your applications config function will allow data passed to a custom dialog to retain its two-way binding with the scope of the calling controller.</span></div><div class="modal-footer"><button type="button" class="btn btn-default" ng-click="done()">Done</button></div>');
  		$templateCache.put('/dialogs/submit_project_options.html','<div class="modal-header dialog-header-confirm"><h4 class="modal-title"><span class="glyphicon glyphicon-check"></span>&nbsp;{{title}}</h4></div><div class="modal-body"><div class="modal-body-text">{{text}}</div><div class="modal-option"><div class="btn-group"><label class="btn btn-default" ng-model="options.returnSubmissions" btn-radio="true">On</label><label class="btn btn-danger" ng-model="options.returnSubmissions" btn-radio="false">Off</label></div><span class="modal-option-label">Will <span ng-if="!options.returnSubmissions">NOT</span> return submissions to designers</span></div><div class="modal-option"><div class="btn-group"><label class="btn btn-default" ng-class="{disabled: !options.returnSubmissions}" ng-model="options.sendNotification" btn-radio="true">On</label><label class="btn btn-danger" ng-class="{disabled: !options.returnSubmissions}" ng-model="options.sendNotification" btn-radio="false">Off</label></div><span class="modal-option-label" ng-class="{disabled: !options.returnSubmissions}">Will <span ng-if="!options.sendNotification">NOT</span> send notification to designers</span></div></div><div class="modal-footer"><button type="button" class="btn btn-default" ng-click="submit()" ng-disabled="(nameDialog.$dirty && nameDialog.$invalid) || nameDialog.$pristine">Yes</button><button type="button" class="btn btn-primary" ng-click="cancel()">No</button></div>');
	}]); 