package com.f9g4.domain;

public enum AdLookTypesEnum {
	ISO_COUNTRY,	   
	ISO_LANGUAGES,	   
	MEM_PAYMENT_STATUS,
	USER_SKILLS,   
	USER_SEC_QUESTION1, 
	USER_SEC_QUESTION2, 
	USER_SEC_QUESTION3,
	REG_STATUS,	   
	MEMBERSHIP_TYPES,   
	USER_TYPES,	   
	MEM_TERM_TYPE,	   
	SALE_TYPE,	   
	MESSAGE_STATUS,	   
	EMAIL_STATUS,	   
	RATE_TRANSACTION,   
	RATING_QUESTION1,   
	RATING_QUESTION2,   
	RATING_QUESTION3,   
	RATING_QUESTION4,   
	RATING_QUESTION5
}
